print("pegue uma panela")
print("despeje 500ml de água")
print("ponha para ferver")
print("aguarde fervura")
print("pegue um pacote de miojo, abra e ponha na pela fervente")
print("aguarde por 3 minutos")
print("drene quase toda a água e despeje o pó")
print("mexa até misturar")
print("está pronto")
