print ("vamos calcular o seu indice de massa corporal ")
altura = float(input ("Diga-nos sua altura "))
peso=float(input('diga-nos seu peso ' ))
imc= peso / (altura * altura)
print(f"Seu idice de massa corporal é {round(imc,2)}")